create table if not exists categories
(
    id bigint primary key generated by default as identity unique ,
    name varchar not null
);

create table if not exists brands
(
    id bigint primary key generated by default as identity unique ,
    title varchar not null ,
    image varchar not null ,
    website varchar not null ,
    description varchar not null
);

create table if not exists cars
(
    id bigint primary key generated by default as identity unique ,
    title varchar not null ,
    brand_id bigint not null ,
    category_id bigint not null ,
    image varchar not null ,
    webpage varchar not null ,
    description varchar not null ,
    price integer not null check ( price >= 0 ) ,
    foreign key (brand_id) references brands(id) on UPDATE cascade on DELETE cascade ,
    foreign key (category_id) references categories(id) on UPDATE cascade on DELETE cascade
);

create table if not exists tags
(
    id bigint primary key generated by default as identity unique ,
    name varchar not null
);

create table if not exists cars_tags
(
    car_id bigint not null ,
    tag_id bigint not null ,
    primary key (car_id, tag_id) ,
    foreign key (car_id) references cars(id) on UPDATE cascade on DELETE cascade ,
    foreign key (tag_id) references tags(id) on UPDATE cascade on DELETE cascade
);

insert into categories(name) values ('Compact'),('Hatchback'),('Coupe'),('Sedan'),('Wagon'),('Sport Car'),('Convertible'),
                                    ('Pickup'), ('Truck'), ('SUV'), ('Limousin');

insert into brands(title, image, website, description)
VALUES ('BMW','https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/BMW.svg/2048px-BMW.svg.png',
        'https://www.bmw.ru/ru/index.html',
        'Концерн BMW Group, в который входят бренды BMW, Mini, Rolls-Royce и BMW Motorrad, является ведущим мировым ' ||
        'производителем автомобилей и мотоциклов, а также поставщиком финансовых услуг и услуг по обеспечению ' ||
        'мобильности премиум-класса. Штат компании насчитывает порядка 125 000 сотрудников в подразделениях по всему миру.');

insert into brands(title, image, website, description)
values ('Audi', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Audi_logo_detail.svg/1280px-Audi_logo_detail.svg.png',
        'https://www.audi.com/en.html',
        'Audi AG is a German automotive manufacturer of luxury vehicles headquartered in Ingolstadt, Bavaria, Germany. ' ||
        'A subsidiary of the Volkswagen Group, Audi produces vehicles in nine production facilities worldwide.');

insert into brands(title, image, website, description)
values ('Mercedes', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Mercedes-Logo.svg/2048px-Mercedes-Logo.svg.png',
        'https://group.mercedes-benz.com/en/',
        'The Mercedes-Benz Group AG (former Daimler AG) is one of the world''s most successful automotive companies. ' ||
        'With Mercedes-Benz AG, we are one of the leading global suppliers of high-end passenger cars and premium vans. ' ||
        'Mercedes-Benz Mobility AG offers financing, leasing, car subscription and car rental, fleet management, ' ||
        'digital services for charging and payment, insurance brokerage, as well as innovative mobility services.');

insert into cars(title, brand_id, category_id, image, webpage, description, price)
VALUES ('M5', 1, 4, 'https://imgd.aeplcdn.com/1280x720/cw/ec/33136/BMW-M5-Exterior-172905.jpg?wm=0&q=80',
        'https://www.bmw.ru/ru/all-models/m-series/m5-sedan/2021/bmw-5-series-sedan-m-automobiles-overview.html',
        'Автомобили M BMW 5 серии впечатляющим образом сочетают в себе фирменную спортивность BMW M с комфортом ' ||
        'и элегантностью седана бизнес-класса. Познакомьтесь с тремя уникальными автомобилями BMW M с яркими характерами. ' ||
        'Быстрейший в истории, новый BMW M5 CS с двигателем мощностью в 635 л.с. (467 кВт) и разгоном до 100 км/ч ' ||
        'за рекордные 3 секунды. Оснащенный двигателем мощностью 625 л.с. (460 кВт) и подвеской с гоночными настройками ' ||
        'BMW M5 Competition с системой полного привода M xDrive олицетворяет собой эталон динамики. ' ||
        'Во внешнем облике высокомощного спортивного седана это проявляется за счет множества элементов цвета "Глянцевый Черный". ' ||
        'В дополнение к системе полного привода M xDrive, спроектированной для максимальной динамики и устойчивости, ' ||
        'BMW M5 оснащается подвеской, обеспечивающей спортивность и комфорт даже в продолжительных поездках. ' ||
        'Завершает тройку BMW M550i xDrive. Этот спортивный седан BMW 5 серии обладает мощностью 530 л.с. (390 кВт) ' ||
        'и впечатляет идеально сбалансированной комбинацией спортивности, комфорта и экономичности.', 11450000);

insert into cars(title, brand_id, category_id, image, webpage, description, price)
values ('R8', 2, 6, 'https://imgd.aeplcdn.com/664x374/cw/ec/21724/Audi-R8-Right-Front-Three-Quarter-66713.jpg?v=201711021421&q=80',
        'https://www.audiusa.com/us/web/en/models/r8/r8-heritage/2024/overview.html',
        'The Audi R8 is a mid-engine, 2-seater sports car, which uses Audi''s trademark quattro permanent ' ||
        'all-wheel drive system. It was introduced by the German car manufacturer Audi AG in 2006. ' ||
        'Production ended in the first quarter of 2024.', 9000000);

insert into cars(title, brand_id, category_id, image, webpage, description, price)
values ('M4', 1, 3, 'https://prod.cosy.bmw.cloud/bmwweb/cosySec?COSY-EU-100-' ||
                    '7331cqgv2Z7d%25i02uCaY3MuO2kOHUtWPfbYf0jD110tLhu1XzWVo7puMLWFmdkAj5DOP5tpsZ8XgY1nTNIowJ4HO3zkyXq%25' ||
                    'sGM8snGhMQSk%2508Xc9Vo74giU2NF1VgxNJ0%25lJfVZ8XJaFBVKLB9MEWO5GalL7GqGAt6GCrv0s9O9DJE4GA0ogRxQNF9OA' ||
                    'LUollkIogOybLKynvLUgChSXF5GybUEqgtc89ChbNmKXNPoEqhk7BRKMLNmqn1cSJDyk7m5VKJXYCn178zBPltE5V1PaHVqfN8z' ||
                    'VMRJw9SkPazDxK07dnMRaYWB9EQ5DxRte2LcZ8YWxfjfEgcPteWS6GERKMfjedw9hbBDS6jQ%250502Ydw6Zuj8KptQ%25wc3l' ||
                    'LMifZu%25KXsyTHSc3uBr0UTJdKX324BDpTQLXg7AF3D%25zhrLGwg6QuiVpRBn5Y3','https://www.bmw.ru/ru/index.html',
        'Автомобили M BMW 4 серии Coupe впечатляющим образом сочетают в себе эстетическую привлекательность, ' ||
        'харизму и фирменный спортивный стиль M. Возглавляет трио BMW M4 Competition Coupe с впечатляющими 510 л.с. ' ||
        'мощности и 650 Нм крутящего момента. Этот автомобиль, оснащенный высокомощным двигателем BMW M TwinPower Turbo, ' ||
        '8-ступенчатой АКПП M Steptronic с технологией Drivelogic, опциональной системой полного привода M xDrive*, ' ||
        'активным дифференциалом M и многочисленными технологиями, позаимствованными в автоспорте, гарантирует ' ||
        'максимальные динамические характеристики – как в повседневной эксплуатации, так и на гоночных трассах. ' ||
        'Завершает модельный ряд BMW M440i xDrive Coupe: помимо привлекательного дизайна это спортивное купе ' ||
        'мощностью 387 л.с. впечатляет особенно сбалансированным сочетанием атлетизма, экономичности и практичности ' ||
        'в повседневной эксплуатации. *M xDrive предлагается ориентировочно с лета 2021 года.', 9000000);

insert into cars(title, brand_id, category_id, image, webpage, description, price)
values ('AMG G-63', 3, 11, 'https://platform.cstatic-images.com/xlarge/in/v2/stock_photos/799a84ca-4aec-4459-8984-' ||
                           '41bea8603148/34dd2126-c630-4221-a3e2-f711ab4149c2.png','https://www.mercedes-benz.com/en/vehicles/g-class/',
        'Mercedes-Benz G 450 d | Energieverbrauch kombiniert: 10,0-8,7 l/100 km | CO2-Emissionen kombiniert: 261-227 g/km ' ||
        '| CO2-Klasse: G; Mercedes-AMG G 63 | Energieverbrauch kombiniert: 15,7-14,7l/100 km | CO2-Emissionen kombiniert: ' ||
        '358-335g/km | CO2-Klasse: G; Mercedes-Benz G 500 | Energieverbrauch kombiniert: 12,3-10,9l/100 km |CO2-Emissionen ' ||
        'kombiniert: 281-248g/km | CO2-Klasse: G', 17099684);

insert into cars(title, brand_id, category_id, image, webpage, description, price)
values ('CLS 63 AMG', 3, 4, 'https://platform.cstatic-images.com/xlarge/in/v2/stock_photos/d70fc0aa-3936-44d1-809b-' ||
                            'd09a4bfaf3c5/4e731530-0992-41b9-bf7e-2ab2e70c2ff9.png', 'https://panavto-mercedes.ru/' ||
                                                                                     'new_cars/cls-class/cls-63-amg-cls-class/',
        'CLS 63 AMG отличается динамическими характеристиками экстра-класса: автомобиль разгоняется с нуля до 100 км/ч ' ||
        'за 4,4 секунды, а максимальная скорость составляет 250 км/ч. Для покупателей CLS 63 AMG дополнительно ' ||
        'предлагается эксклюзивный пакет оснащения AMG Performance Package.', 10450000);

insert into tags(name) values ('спорт'),('внедорожник'),('седан'),('купе'),('полный привод'),('задний привод'),('передний привод'),
                              ('механика'),('автомат'),('спорт кар'),('комфорт'),('стиль'),('two doors'),('speed'),('solid'),
                              ('beautiful'),('phenomenal');

insert into cars_tags values (4,2),(4,5),(4,11),(4,12),(4,8),(2,1),(2,10),(2,5),(2,12),(2,4),(3,1),(3,4),(1,3),(1,9),(1,11),
                             (1,1),(1,12),(3,5),(3,9),(3,12),(3,13),(2,14),(5,16),(5,3),(5,9),(5,15),(5,5),(5,11);